name: WebdriverIO Test

on:
  push:
    branches: [ master, release]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Docker Image
        run: docker build -t my-webdriverio .
      - name: Delete Docker Container
        run: docker rm -f webdriverio
      - name: WDIO Run
        run: docker run --name webdriverio my-webdriverio sh -c './script/run.sh; ls -all'